# Generated by Django 3.1.3 on 2025-04-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFiles',
            new_name='UploadedFile',
        ),
    ]
